trigger: 
- main

pool: 
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
    - stage: Build
      displayName: Build App
      jobs:
        - job: Build
          steps:
            - task: UseDotNet@2
              displayName: 'Use .NET SDK 6.x'
              inputs:
                  packageType: sdk
                  version: '6.x'
            - task: Npm@1
              displayName: 'Run npm install'
              inputs:
                verbose: false
    - stage: Stage2
      displayName: Test stage
      jobs:
        - job: TestJob
          steps:
            - bash: echo "Test Job - Bash Step"      
                
    

