trigger: 
- main

pool: 
  vmImage: ubuntu-latest


variables:
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '6.x'

stages:
    - stage: Build
      displayName: Build App
      jobs:
        - job: Build
          steps:
            - task: UseDotNet@2
              displayName: 'Use .NET SDK $(dotnetSdkVersion)'
              inputs:
                  packageType: sdk
                  version: '$(dotnetSdkVersion)'
            - task: Npm@1
              displayName: 'Run npm install'
              inputs:
                verbose: false
            
            - task: CmdLine@2
              displayName: 'Compile Sass assets'
              inputs:
                script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
            
            - task: gulp@1
              displayName: 'Run gulp tasks'
            
            #Shortcut for CmdLine@2
            - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
              displayName: 'Write build info'
              workingDirectory: $(wwwrootDir)
            
            - task: DotNetCoreCLI@2
              displayName: 'Restore project dependencies'
              inputs:
                command: 'restore'
                projects: '**/*.csproj'

            - template: Templates/build.yml
              parameters:
                buildConfiguration: 'Debug'

            - template: Templates/build.yml
              parameters:
                buildConfiguration: 'Release'
            
            - task: PublishBuildArtifacts@1
              condition: succeeded()
              inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: 'drop'              
 
    - stage: Test
      displayName: Test stage
      jobs:
        - job: TestJob
          steps:
            - bash: echo "Test Job - Bash Step"      